// Fixed taxonomies that live IN CODE, never generated by the model.
// plan.md L190: "Constrain worldcover_class to the exact 11-class enum. Keep
// WorldCover->IPCC AFOLU crosswalk in code." plan.md L189: "a fixed lever-type
// taxonomy so it cannot invent freeform mechanisms."
//
// Client-safe (no @google/genai import) so UI + validators + the Gemini schema
// can all share these without bundling the SDK.

// ── ESA WorldCover v200 — the canonical 11-class land-cover enum ──
export const WORLDCOVER_CLASSES = [
  "Tree cover",
  "Shrubland",
  "Grassland",
  "Cropland",
  "Built-up",
  "Bare / sparse vegetation",
  "Snow and ice",
  "Permanent water bodies",
  "Herbaceous wetland",
  "Mangroves",
  "Moss and lichen",
] as const;
export type WorldCoverClass = (typeof WORLDCOVER_CLASSES)[number];

// The map value carries the official raster code alongside the IPCC AFOLU
// crosswalk, so a single lookup gives both.
export const WORLDCOVER: Record<
  WorldCoverClass,
  { code: number; ipcc: IpccAfoluClass }
> = {
  "Tree cover": { code: 10, ipcc: "Forest land" },
  Shrubland: { code: 20, ipcc: "Grassland" },
  Grassland: { code: 30, ipcc: "Grassland" },
  Cropland: { code: 40, ipcc: "Cropland" },
  "Built-up": { code: 50, ipcc: "Settlements" },
  "Bare / sparse vegetation": { code: 60, ipcc: "Other land" },
  "Snow and ice": { code: 70, ipcc: "Other land" },
  "Permanent water bodies": { code: 80, ipcc: "Wetlands" },
  "Herbaceous wetland": { code: 90, ipcc: "Wetlands" },
  Mangroves: { code: 95, ipcc: "Wetlands" }, // IPCC treats mangroves as coastal wetlands
  "Moss and lichen": { code: 100, ipcc: "Other land" },
} as const;

// ── IPCC AFOLU — the 6 land-use categories WorldCover maps into ──
export const IPCC_AFOLU_CLASSES = [
  "Forest land",
  "Cropland",
  "Grassland",
  "Wetlands",
  "Settlements",
  "Other land",
] as const;
export type IpccAfoluClass = (typeof IPCC_AFOLU_CLASSES)[number];

export function worldcoverToIpcc(cls: WorldCoverClass): IpccAfoluClass {
  return WORLDCOVER[cls].ipcc;
}

// ── Fixed lever-type taxonomy — the leash on "secret levers" (plan.md L189) ──
// A closed set so Gemini classifies a mechanism instead of inventing a freeform
// one. Covers the non-obvious economic levers the demo hook depends on
// (fiscal budgets, subsidies, zoning) without an open vocabulary.
export const LEVER_TYPES = [
  "land_use_control", // zoning, protected-area designation, moratoria
  "fiscal", // budgets, appropriations, taxes on activity
  "subsidy", // ag/energy subsidies, PES payments, incentives
  "regulatory", // licensing, standards, bans, permits
  "enforcement", // monitoring, fines, policing capacity
  "market_incentive", // carbon markets, tradable credits, tariffs
  "infrastructure", // roads, grid, transport that unlock/lock land use
  "information", // disclosure, reporting, transparency requirements
] as const;
export type LeverType = (typeof LEVER_TYPES)[number];

// ── Shared enums used across the contract ──
export const CHANGE_MAGNITUDE_ORDINAL = [
  "none",
  "slight",
  "moderate",
  "large",
  "unknown",
] as const;
export type ChangeMagnitudeOrdinal = (typeof CHANGE_MAGNITUDE_ORDINAL)[number];

export const CHANGE_DIRECTION = ["increase", "decrease", "mixed", "none", "unknown"] as const;
export type ChangeDirection = (typeof CHANGE_DIRECTION)[number];

export const CONFIDENCE_ENUM = ["low", "medium", "high"] as const;
export type ConfidenceEnum = (typeof CONFIDENCE_ENUM)[number];

// Emission direction is about the lever's climate effect, distinct from the
// land-cover-area change_direction above.
export const EMISSION_DIRECTION = [
  "increases_emissions",
  "decreases_emissions",
  "ambiguous",
] as const;
export type EmissionDirection = (typeof EMISSION_DIRECTION)[number];

// ── The one discipline that makes the whole thing defensible (plan.md L26) ──
// Every number carries one of these; the UI's "receipts mode" renders them.
export const PROVENANCE_TAGS = ["OBSERVED", "MODELED", "LLM_NARRATIVE"] as const;
export type ProvenanceTag = (typeof PROVENANCE_TAGS)[number];
